import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  contributeSidebar: [
    {
      type: 'doc',
      id: 'contribute',
      label: 'Внести вклад',
    },
  ],
};

export default sidebars;
